GET http://localhost:8080/Home
Accept: application/json

###
GET http://localhost:8080/Home/Calculate?a=1&b=2
Accept: application/json

###
GET http://localhost:8080/Home/Calculate?a=3&b=4
Accept: application/json
